### ISSUE TITLE
Schema produces `bool` type, but Avro format expects `boolean`

### ISSUE THREAD

**Issue by hcarvalhoalves** [maxpoint/cyavro#14]
The function `infer_avro_schema_for_dataframe` produces the following output if a pandas.Series has dtype `bool`:

`{"name":"is_customer", "type": "bool"},`

But according to Avro's documentation the type should be `boolean`: https://avro.apache.org/docs/1.8.1/spec.html#schema_primitive

**Comment by mariusvniekerk** [comment]
I've merged a fix to master for this.

**Comment by hcarvalhoalves** [comment]
Tks @mariusvniekerk 👍
