### ISSUE TITLE
Set up builds on anaconda.org

### ISSUE THREAD

**Issue by mariusvniekerk** [maxpoint/cyavro#8]
Would be nice to have working build on binstar for this

**Comment by danielfrg** [comment]
I would recommend to take a look at conda-forge: https://github.com/conda-forge now instead of the anaconda.org builders. It should be quite easy to move your conda recipe there.

**Comment by mariusvniekerk** [comment]
Yeah I have builds on anaconda.org ATM and they work, but I should probably just use conda-forge

**Comment by mariusvniekerk** [comment]
Conda forge being set up here https://github.com/conda-forge/staged-recipes/pull/738

**Comment by mariusvniekerk** [comment]
@danielfrg what do i need to change to allow the --single-version-externally managed?

Do i need to use setuptools instead of distutils?

**Comment by danielfrg** [comment]
Yes, if you are using setuptools you need to use that flag. If you use distutils you don't need it.

**Comment by mariusvniekerk** [comment]
Now that its on conda-forge anaconda.org builds are no longer needed
