### ISSUE TITLE
Support Python 3?

### ISSUE THREAD

**Issue by michael-erasmus** [maxpoint/cyavro#9]
Seeing the following error if I try the `write_avro_file_from_dataframe` function on Python 3.5.1

```
/opt/conda/lib/python3.5/site-packages/cyavro/__init__.py in <genexpr>(.0)
    465             elif issubclass(tp, dict):
    466                 # get value element type
--> 467                 values = (x.itervalues() for x in iterable)
    468                 value_type = _get_python_type(list(itertools.chain.from_iterable(values)))
    469                 return '{{"type": "map", "values": {} }}'.format(value_type)

AttributeError: 'dict' object has no attribute 'itervalues'
```

Any plans to support Python 3? I would love to easily read/write Avro files from Pandas Dataframes, but unfortunately I don't have the option of using Python 2 :/

**Comment by mariusvniekerk** [comment]
that should be easy enough to fix using six

**Comment by mariusvniekerk** [comment]
This has been addressed with #10 .  Release is available on pypi.  Anaconda.org builds are coming but they can take a while.

**Comment by michael-erasmus** [comment]
Wow, thanks so much for the quick fix! Will try it out today!

**Comment by mariusvniekerk** [comment]
@michael-erasmus So did this solve your issue?
